### ISSUE TITLE
inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by edloginova** [libindic/Transliteration#18]
Python 3.6
```
from transliteration import getInstance
t = getInstance()
text = "पीला"
t_text = t.transliterate_en_hi(text)
print(t_text)

```
Traceback (most recent call last):

  File "/home/mlt/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-23-38929420e7df>", line 1, in <module>
    from transliteration import getInstance

  File "/home/mlt/anaconda3/lib/python3.6/site-packages/transliteration/__init__.py", line 4, in <module>
    from transliteration.core import Transliterator, getInstance

  File "/home/mlt/anaconda3/lib/python3.6/site-packages/transliteration/core.py", line 28, in <module>
    import normalizer

  File "/home/mlt/anaconda3/lib/python3.6/site-packages/normalizer/__init__.py", line 2, in <module>
    from  normalizer.core import Normalizer,getInstance

  File "/home/mlt/anaconda3/lib/python3.6/site-packages/normalizer/core.py", line 59
    text = unicode( rules_file.readline())
                                          ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by AfrahAsif** [comment]
Were you able to solve this issue?

**Comment by edloginova** [comment]
I think I had to rewrite the code, would you like me to share it?

**Comment by raikarsagar** [comment]
Please share it

**Comment by asdofindia** [comment]
This seems like a problem in normalizer package. Anyhow the source code of normalizer doesn't have this bug at the moment. So, closing this.
